
package com.jaxws.detector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DumbDetector", targetNamespace = "http://detector.jaxws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DumbDetector {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.jaxws.detector.Capability
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guess", targetNamespace = "http://detector.jaxws.com/", className = "com.jaxws.detector.Guess")
    @ResponseWrapper(localName = "guessResponse", targetNamespace = "http://detector.jaxws.com/", className = "com.jaxws.detector.GuessResponse")
    @Action(input = "http://detector.jaxws.com/DumbDetector/guessRequest", output = "http://detector.jaxws.com/DumbDetector/guessResponse")
    public Capability guess(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.jaxws.detector.Capability
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "detect", targetNamespace = "http://detector.jaxws.com/", className = "com.jaxws.detector.Detect")
    @ResponseWrapper(localName = "detectResponse", targetNamespace = "http://detector.jaxws.com/", className = "com.jaxws.detector.DetectResponse")
    @Action(input = "http://detector.jaxws.com/DumbDetector/detectRequest", output = "http://detector.jaxws.com/DumbDetector/detectResponse")
    public Capability detect(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

}
